title: "Joseph295 的博客"
subtitle: "共潮生"
description: "记录学习与思考"
language: zh-CN
timezone: "Asia/Shanghai"

url: https://Joseph295.github.io
root: /

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories

new_post_name: :title.md
default_layout: post
highlight:
  enable: true
  line_number: true
  auto_detect: true

theme: next

deploy:
  type: ""  # 使用 GitHub Actions 部署，不使用 hexo-deployer-git

